export default [
  {
    files: ['src/**/*.js', 'tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        Blob: 'readonly',
        document: 'readonly',
        Event: 'readonly',
        HTMLElement: 'readonly',
        KeyboardEvent: 'readonly',
        localStorage: 'readonly',
        MouseEvent: 'readonly',
        navigator: 'readonly',
        queueMicrotask: 'readonly',
        sessionStorage: 'readonly',
        clearTimeout: 'readonly',
        setTimeout: 'readonly',
        TextEncoder: 'readonly',
        URL: 'readonly',
        __dirname: 'readonly',
        __APP_VERSION__: 'readonly',
        __BUILD_MONTH__: 'readonly',
        afterEach: 'readonly',
        beforeEach: 'readonly',
        describe: 'readonly',
        expect: 'readonly',
        it: 'readonly',
        vi: 'readonly',
        window: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': 'error',
    },
  },
];
