import { db } from './db.js';

const DEMO_RECORDS = [
  {
    company_name: 'Acme Corp',
    job_title: 'Frontend Engineer',
    status: 'applied',
    compat: 85,
    fav: 1,
    salary: '$120,000 – $140,000',
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/acme-fe',
    recruiter: 'Jane Smith',
    notes: 'Strong culture fit. Hybrid role, 2 days in office.',
    responsibilities: 'Build and maintain component library, own frontend CI pipeline.',
    skills: JSON.stringify(['React', 'TypeScript', 'CSS', 'Vite']),
    application_date: '2026-04-10',
    last_status_update: '2026-04-12',
    created_at: '2026-04-10',
    updated_at: '2026-04-12',
    archived: 0,
  },
  {
    company_name: 'Beta Systems',
    job_title: 'Backend Engineer',
    status: 'interview',
    compat: 72,
    fav: 0,
    salary: '$130,000 – $155,000',
    source_platform: 'Indeed',
    job_posting_url: 'https://jobs.example.com/beta-backend',
    recruiter: 'Tom Lee',
    notes: 'Second round scheduled for next week. Panel format.',
    responsibilities: 'Design REST APIs, own DB migrations, participate in on-call rotation.',
    skills: JSON.stringify(['Node.js', 'PostgreSQL', 'Docker', 'AWS']),
    application_date: '2026-03-28',
    last_status_update: '2026-04-18',
    created_at: '2026-03-28',
    updated_at: '2026-04-18',
    archived: 0,
  },
  {
    company_name: 'Gamma Digital',
    job_title: 'Full Stack Developer',
    status: 'offer',
    compat: 91,
    fav: 1,
    salary: '$145,000',
    source_platform: 'Referral',
    job_posting_url: null,
    recruiter: 'Maria Chen',
    notes: 'Verbal offer received. Deadline to accept: 2026-05-01.',
    responsibilities: 'End-to-end ownership of 2 product squads. React + Node.',
    skills: JSON.stringify(['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Redis']),
    application_date: '2026-03-15',
    last_status_update: '2026-04-22',
    created_at: '2026-03-15',
    updated_at: '2026-04-22',
    archived: 0,
  },
  {
    company_name: 'Delta Cloud',
    job_title: 'DevOps Engineer',
    status: 'phone_screen',
    compat: 60,
    fav: 0,
    salary: '$110,000 – $125,000',
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/delta-devops',
    recruiter: null,
    notes: 'Initial call with HR went well. Waiting for technical screen invite.',
    responsibilities: 'Maintain CI/CD pipelines, manage Kubernetes clusters on GCP.',
    skills: JSON.stringify(['Kubernetes', 'Terraform', 'GCP', 'Python']),
    application_date: '2026-04-14',
    last_status_update: '2026-04-20',
    created_at: '2026-04-14',
    updated_at: '2026-04-20',
    archived: 0,
  },
  {
    company_name: 'Epsilon AI',
    job_title: 'ML Engineer',
    status: 'assessment',
    compat: 78,
    fav: 0,
    salary: '$150,000 – $175,000',
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/epsilon-ml',
    recruiter: 'Priya Nair',
    notes: 'Take-home project due 2026-04-30. Build a small recommendation engine.',
    responsibilities: 'Train and ship production ML models, collaborate with data platform team.',
    skills: JSON.stringify(['Python', 'PyTorch', 'SQL', 'MLflow']),
    application_date: '2026-04-05',
    last_status_update: '2026-04-19',
    created_at: '2026-04-05',
    updated_at: '2026-04-19',
    archived: 0,
  },
  {
    company_name: 'Zeta Health',
    job_title: 'Software Engineer',
    status: 'wishlisted',
    compat: 55,
    fav: 0,
    salary: null,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/zeta-swe',
    recruiter: null,
    notes: 'Interesting mission. Not ready to apply — revisit after current round.',
    responsibilities: null,
    skills: JSON.stringify(['Python', 'Django', 'React']),
    application_date: null,
    last_status_update: '2026-04-23',
    created_at: '2026-04-23',
    updated_at: '2026-04-23',
    archived: 0,
  },
  {
    company_name: 'Eta Retail',
    job_title: 'Platform Engineer',
    status: 'rejected',
    compat: 40,
    fav: 0,
    salary: '$115,000',
    source_platform: 'Indeed',
    job_posting_url: null,
    recruiter: 'Chris Park',
    notes: 'Generic rejection email. Role required more Java experience.',
    responsibilities: 'Internal tooling and developer platform for 200-person eng org.',
    skills: JSON.stringify(['Java', 'Spring Boot', 'Kafka']),
    application_date: '2026-03-10',
    last_status_update: '2026-04-01',
    created_at: '2026-03-10',
    updated_at: '2026-04-01',
    archived: 0,
  },
  {
    company_name: 'Theta Finance',
    job_title: 'Senior Engineer',
    status: 'ghosted',
    compat: 65,
    fav: 0,
    salary: '$140,000',
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/theta-sre',
    recruiter: 'Alex Wong',
    notes: 'No response after onsite interview on 2026-03-22. Followed up twice.',
    responsibilities: 'Lead reliability initiatives across payment services.',
    skills: JSON.stringify(['Go', 'Kubernetes', 'Prometheus', 'PostgreSQL']),
    application_date: '2026-03-05',
    last_status_update: '2026-03-22',
    created_at: '2026-03-05',
    updated_at: '2026-04-05',
    archived: 0,
  },
  {
    company_name: 'Iota Media',
    job_title: 'React Developer',
    status: 'withdrawn',
    compat: 50,
    fav: 0,
    salary: '$105,000',
    source_platform: 'Referral',
    job_posting_url: null,
    recruiter: 'Sam Rivera',
    notes: 'Withdrew after receiving the Gamma Digital offer.',
    responsibilities: 'Build consumer-facing video streaming UI.',
    skills: JSON.stringify(['React', 'GraphQL', 'Next.js']),
    application_date: '2026-03-20',
    last_status_update: '2026-04-23',
    created_at: '2026-03-20',
    updated_at: '2026-04-23',
    archived: 0,
  },
  {
    company_name: 'Kappa Labs',
    job_title: 'Engineering Manager',
    status: 'applied',
    compat: 68,
    fav: 0,
    salary: '$160,000 – $180,000',
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/kappa-em',
    recruiter: null,
    notes: 'Exploratory — not actively pursuing management yet.',
    responsibilities: 'Lead a team of 6 engineers on the data platform.',
    skills: JSON.stringify(['Team leadership', 'Node.js', 'Python']),
    application_date: '2026-04-08',
    last_status_update: '2026-04-08',
    created_at: '2026-04-08',
    updated_at: '2026-04-08',
    archived: 1,
  },
];

const COLUMNS = [
  'company_name', 'job_title', 'status', 'compat', 'fav',
  'salary', 'source_platform', 'job_posting_url', 'recruiter',
  'notes', 'responsibilities', 'skills',
  'application_date', 'last_status_update', 'created_at', 'updated_at', 'archived',
];

try {
  const cleared = db.prepare('DELETE FROM applications').run();
  console.log(`Cleared ${cleared.changes} existing record(s).`);

  const insert = db.prepare(`
    INSERT INTO applications (${COLUMNS.join(', ')})
    VALUES (${COLUMNS.map((c) => `@${c}`).join(', ')})
  `);

  const insertMany = db.transaction((records) => {
    for (const record of records) {
      insert.run(record);
    }
  });

  insertMany(DEMO_RECORDS);
  db.close();

  console.log(`Seeded ${DEMO_RECORDS.length} demo records.`);
  process.exit(0);
} catch (error) {
  console.error(error);
  process.exit(1);
}
