import { db } from './db.js';

const DEMO_RECORDS = [
  {
    company_name: 'Acme Corp',
    job_title: 'Frontend Engineer',
    status: 'applied',
    compat: 85,
    fav: 1,
    salary: 120000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/acme-fe',
    recruiter: 'Jane Smith',
    notes: 'Strong culture fit. Hybrid role, 2 days in office.',
    responsibilities: 'Build and maintain component library, own frontend CI pipeline.',
    skills: JSON.stringify(['React', 'TypeScript', 'CSS', 'Vite']),
    application_date: '2026-04-10',
    last_status_update: '2026-04-12',
    created_at: '2026-04-10',
    updated_at: '2026-04-12',
    archived: 0,
  },
  {
    company_name: 'Beta Systems',
    job_title: 'Backend Engineer',
    status: 'interview',
    compat: 72,
    fav: 0,
    salary: 130000,
    source_platform: 'Indeed',
    job_posting_url: 'https://jobs.example.com/beta-backend',
    recruiter: 'Tom Lee',
    notes: 'Second round scheduled for next week. Panel format.',
    responsibilities: 'Design REST APIs, own DB migrations, participate in on-call rotation.',
    skills: JSON.stringify(['Node.js', 'PostgreSQL', 'Docker', 'AWS']),
    application_date: '2026-03-28',
    last_status_update: '2026-04-18',
    created_at: '2026-03-28',
    updated_at: '2026-04-18',
    archived: 0,
  },
  {
    company_name: 'Gamma Digital',
    job_title: 'Full Stack Developer',
    status: 'offer',
    compat: 91,
    fav: 1,
    salary: 145000,
    source_platform: 'Referral',
    job_posting_url: null,
    recruiter: 'Maria Chen',
    notes: 'Verbal offer received. Deadline to accept: 2026-05-01.',
    responsibilities: 'End-to-end ownership of 2 product squads. React + Node.',
    skills: JSON.stringify(['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Redis']),
    application_date: '2026-03-15',
    last_status_update: '2026-04-22',
    created_at: '2026-03-15',
    updated_at: '2026-04-22',
    archived: 0,
  },
  {
    company_name: 'Delta Cloud',
    job_title: 'DevOps Engineer',
    status: 'phone_screen',
    compat: 60,
    fav: 0,
    salary: 110000,
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/delta-devops',
    recruiter: null,
    notes: 'Initial call with HR went well. Waiting for technical screen invite.',
    responsibilities: 'Maintain CI/CD pipelines, manage Kubernetes clusters on GCP.',
    skills: JSON.stringify(['Kubernetes', 'Terraform', 'GCP', 'Python']),
    application_date: '2026-04-14',
    last_status_update: '2026-04-20',
    created_at: '2026-04-14',
    updated_at: '2026-04-20',
    archived: 0,
  },
  {
    company_name: 'Epsilon AI',
    job_title: 'ML Engineer',
    status: 'assessment',
    compat: 78,
    fav: 0,
    salary: 150000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/epsilon-ml',
    recruiter: 'Priya Nair',
    notes: 'Take-home project due 2026-04-30. Build a small recommendation engine.',
    responsibilities: 'Train and ship production ML models, collaborate with data platform team.',
    skills: JSON.stringify(['Python', 'PyTorch', 'SQL', 'MLflow']),
    application_date: '2026-04-05',
    last_status_update: '2026-04-19',
    created_at: '2026-04-05',
    updated_at: '2026-04-19',
    archived: 0,
  },
  {
    company_name: 'Zeta Health',
    job_title: 'Software Engineer',
    status: 'wishlisted',
    compat: 55,
    fav: 0,
    salary: null,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/zeta-swe',
    recruiter: null,
    notes: 'Interesting mission. Not ready to apply — revisit after current round.',
    responsibilities: null,
    skills: JSON.stringify(['Python', 'Django', 'React']),
    application_date: null,
    last_status_update: '2026-04-23',
    created_at: '2026-04-23',
    updated_at: '2026-04-23',
    archived: 0,
  },
  {
    company_name: 'Eta Retail',
    job_title: 'Platform Engineer',
    status: 'rejected',
    compat: 40,
    fav: 0,
    salary: 115000,
    source_platform: 'Indeed',
    job_posting_url: null,
    recruiter: 'Chris Park',
    notes: 'Generic rejection email. Role required more Java experience.',
    responsibilities: 'Internal tooling and developer platform for 200-person eng org.',
    skills: JSON.stringify(['Java', 'Spring Boot', 'Kafka']),
    application_date: '2026-03-10',
    last_status_update: '2026-04-01',
    created_at: '2026-03-10',
    updated_at: '2026-04-01',
    archived: 0,
  },
  {
    company_name: 'Theta Finance',
    job_title: 'Senior Engineer',
    status: 'ghosted',
    compat: 65,
    fav: 0,
    salary: 140000,
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/theta-sre',
    recruiter: 'Alex Wong',
    notes: 'No response after onsite interview on 2026-03-22. Followed up twice.',
    responsibilities: 'Lead reliability initiatives across payment services.',
    skills: JSON.stringify(['Go', 'Kubernetes', 'Prometheus', 'PostgreSQL']),
    application_date: '2026-03-05',
    last_status_update: '2026-03-22',
    created_at: '2026-03-05',
    updated_at: '2026-04-05',
    archived: 0,
  },
  {
    company_name: 'Iota Media',
    job_title: 'React Developer',
    status: 'withdrawn',
    compat: 50,
    fav: 0,
    salary: 105000,
    source_platform: 'Referral',
    job_posting_url: null,
    recruiter: 'Sam Rivera',
    notes: 'Withdrew after receiving the Gamma Digital offer.',
    responsibilities: 'Build consumer-facing video streaming UI.',
    skills: JSON.stringify(['React', 'GraphQL', 'Next.js']),
    application_date: '2026-03-20',
    last_status_update: '2026-04-23',
    created_at: '2026-03-20',
    updated_at: '2026-04-23',
    archived: 0,
  },
  {
    company_name: 'Kappa Labs',
    job_title: 'Engineering Manager',
    status: 'applied',
    compat: 68,
    fav: 0,
    salary: 160000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/kappa-em',
    recruiter: null,
    notes: 'Exploratory — not actively pursuing management yet.',
    responsibilities: 'Lead a team of 6 engineers on the data platform.',
    skills: JSON.stringify(['Team leadership', 'Node.js', 'Python']),
    application_date: '2026-04-08',
    last_status_update: '2026-04-08',
    created_at: '2026-04-08',
    updated_at: '2026-04-08',
    archived: 1,
  },
  {
    company_name: 'Lambda Ops',
    job_title: 'Site Reliability Engineer',
    status: 'interview',
    compat: 70,
    fav: 0,
    salary: 135000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/lambda-sre',
    recruiter: 'Dana Hill',
    notes: 'Onsite scheduled for 2026-04-29. Will cover incident response and system design.',
    responsibilities: 'Own uptime SLOs for core services, lead post-mortems, build internal tooling.',
    skills: JSON.stringify(['Go', 'Prometheus', 'Grafana', 'Kubernetes', 'PagerDuty']),
    application_date: '2026-04-02',
    last_status_update: '2026-04-21',
    created_at: '2026-04-02',
    updated_at: '2026-04-21',
    archived: 0,
  },
  {
    company_name: 'Mu Technologies',
    job_title: 'iOS Developer',
    status: 'phone_screen',
    compat: 58,
    fav: 0,
    salary: 115000,
    source_platform: 'AngelList',
    job_posting_url: 'https://jobs.example.com/mu-ios',
    recruiter: 'Lena Park',
    notes: 'Recruiter screen done. Stretch role — Swift experience is limited.',
    responsibilities: 'Build and ship new features in the consumer iOS app, coordinate with backend.',
    skills: JSON.stringify(['Swift', 'SwiftUI', 'Xcode', 'REST APIs']),
    application_date: '2026-04-16',
    last_status_update: '2026-04-24',
    created_at: '2026-04-16',
    updated_at: '2026-04-24',
    archived: 0,
  },
  {
    company_name: 'Nu Analytics',
    job_title: 'Data Engineer',
    status: 'assessment',
    compat: 82,
    fav: 0,
    salary: 125000,
    source_platform: 'Indeed',
    job_posting_url: 'https://jobs.example.com/nu-de',
    recruiter: 'Omar Hassan',
    notes: 'SQL + Python take-home. 3-hour window, due 2026-04-28.',
    responsibilities: 'Build and maintain ELT pipelines, partner with analytics and ML teams.',
    skills: JSON.stringify(['Python', 'dbt', 'Airflow', 'BigQuery', 'SQL']),
    application_date: '2026-04-09',
    last_status_update: '2026-04-22',
    created_at: '2026-04-09',
    updated_at: '2026-04-22',
    archived: 0,
  },
  {
    company_name: 'Xi Studio',
    job_title: 'Staff Engineer',
    status: 'wishlisted',
    compat: 83,
    fav: 1,
    salary: 170000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/xi-staff',
    recruiter: null,
    notes: 'Dream role — wait until current round settles before applying.',
    responsibilities: null,
    skills: JSON.stringify(['System design', 'TypeScript', 'Go', 'Distributed systems']),
    application_date: null,
    last_status_update: '2026-04-25',
    created_at: '2026-04-25',
    updated_at: '2026-04-25',
    archived: 0,
  },
  {
    company_name: 'Omicron Bank',
    job_title: 'Java Developer',
    status: 'applied',
    compat: 48,
    fav: 0,
    salary: 118000,
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/omicron-java',
    recruiter: null,
    notes: 'Applied as a backup option. Heavy enterprise Java stack.',
    responsibilities: 'Maintain internal payments processing services using Spring Boot.',
    skills: JSON.stringify(['Java', 'Spring Boot', 'Oracle DB', 'Maven']),
    application_date: '2026-04-17',
    last_status_update: '2026-04-17',
    created_at: '2026-04-17',
    updated_at: '2026-04-17',
    archived: 0,
  },
  {
    company_name: 'Pi Robotics',
    job_title: 'Embedded Software Engineer',
    status: 'rejected',
    compat: 35,
    fav: 0,
    salary: 110000,
    source_platform: 'Indeed',
    job_posting_url: null,
    recruiter: 'Ingrid Sato',
    notes: 'Required 3+ years of C/C++ embedded experience. Not a match.',
    responsibilities: 'Write firmware for motor control systems on custom ARM hardware.',
    skills: JSON.stringify(['C', 'C++', 'RTOS', 'ARM']),
    application_date: '2026-03-18',
    last_status_update: '2026-04-03',
    created_at: '2026-03-18',
    updated_at: '2026-04-03',
    archived: 0,
  },
  {
    company_name: 'Rho Games',
    job_title: 'Game Developer',
    status: 'withdrawn',
    compat: 44,
    fav: 0,
    salary: 95000,
    source_platform: 'Referral',
    job_posting_url: null,
    recruiter: 'Jake Moon',
    notes: 'Withdrew — salary range too low and fully on-site.',
    responsibilities: 'Gameplay systems engineering in Unity for a mobile title.',
    skills: JSON.stringify(['C#', 'Unity', 'Git', 'Agile']),
    application_date: '2026-03-25',
    last_status_update: '2026-04-10',
    created_at: '2026-03-25',
    updated_at: '2026-04-10',
    archived: 0,
  },
  {
    company_name: 'Sigma Cloud',
    job_title: 'Cloud Architect',
    status: 'offer',
    compat: 88,
    fav: 1,
    salary: 165000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/sigma-arch',
    recruiter: 'Rachel Kim',
    notes: 'Competing offer — using to negotiate with Gamma Digital.',
    responsibilities: 'Design multi-region AWS architecture, lead migration from on-prem.',
    skills: JSON.stringify(['AWS', 'Terraform', 'Python', 'CDK', 'Networking']),
    application_date: '2026-03-12',
    last_status_update: '2026-04-20',
    created_at: '2026-03-12',
    updated_at: '2026-04-20',
    archived: 0,
  },
  {
    company_name: 'Tau Security',
    job_title: 'Security Engineer',
    status: 'ghosted',
    compat: 74,
    fav: 0,
    salary: 140000,
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/tau-sec',
    recruiter: 'Victor Olsen',
    notes: 'Completed technical screen on 2026-03-30. No word since.',
    responsibilities: 'Threat modelling, vulnerability management, secure SDLC practices.',
    skills: JSON.stringify(['Python', 'Burp Suite', 'OWASP', 'AWS Security']),
    application_date: '2026-03-22',
    last_status_update: '2026-03-30',
    created_at: '2026-03-22',
    updated_at: '2026-04-10',
    archived: 0,
  },
  {
    company_name: 'Upsilon Dev',
    job_title: 'Software Engineer II',
    status: 'phone_screen',
    compat: 76,
    fav: 0,
    salary: 125000,
    source_platform: 'AngelList',
    job_posting_url: 'https://jobs.example.com/upsilon-swe2',
    recruiter: 'Nadia Flores',
    notes: 'Fast-growing Series B. Engineering team of 15.',
    responsibilities: 'Greenfield product features across the full stack.',
    skills: JSON.stringify(['TypeScript', 'React', 'Node.js', 'PostgreSQL']),
    application_date: '2026-04-18',
    last_status_update: '2026-04-24',
    created_at: '2026-04-18',
    updated_at: '2026-04-24',
    archived: 0,
  },
  {
    company_name: 'Phi Systems',
    job_title: 'Solutions Architect',
    status: 'interview',
    compat: 66,
    fav: 0,
    salary: 155000,
    source_platform: 'LinkedIn',
    job_posting_url: null,
    recruiter: 'Marcus Bell',
    notes: 'Client-facing role — heavier travel than expected. Worth exploring.',
    responsibilities: 'Design enterprise integration solutions, lead pre-sales technical calls.',
    skills: JSON.stringify(['AWS', 'Salesforce', 'REST APIs', 'Solution design']),
    application_date: '2026-04-01',
    last_status_update: '2026-04-19',
    created_at: '2026-04-01',
    updated_at: '2026-04-19',
    archived: 0,
  },
  {
    company_name: 'Chi Networks',
    job_title: 'Senior Network Engineer',
    status: 'applied',
    compat: 42,
    fav: 0,
    salary: 120000,
    source_platform: 'Indeed',
    job_posting_url: 'https://jobs.example.com/chi-net',
    recruiter: null,
    notes: 'Long shot — applied to broaden the pipeline.',
    responsibilities: 'Design and manage enterprise WAN/LAN infrastructure.',
    skills: JSON.stringify(['Cisco', 'BGP', 'OSPF', 'Network security']),
    application_date: '2026-04-21',
    last_status_update: '2026-04-21',
    created_at: '2026-04-21',
    updated_at: '2026-04-21',
    archived: 0,
  },
  {
    company_name: 'Psi Corp',
    job_title: 'Frontend Architect',
    status: 'wishlisted',
    compat: 79,
    fav: 0,
    salary: null,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/psi-fe-arch',
    recruiter: null,
    notes: 'Posted recently. Revisit after the current interview round wraps.',
    responsibilities: null,
    skills: JSON.stringify(['React', 'Micro-frontends', 'Design systems', 'TypeScript']),
    application_date: null,
    last_status_update: '2026-04-26',
    created_at: '2026-04-26',
    updated_at: '2026-04-26',
    archived: 0,
  },
];

const COLUMNS = [
  'company_name', 'job_title', 'status', 'compat', 'fav',
  'salary', 'source_platform', 'job_posting_url', 'recruiter',
  'notes', 'responsibilities', 'skills',
  'application_date', 'last_status_update', 'created_at', 'updated_at', 'archived',
];

try {
  const cleared = db.prepare('DELETE FROM applications').run();
  console.log(`Cleared ${cleared.changes} existing record(s).`);

  const insert = db.prepare(`
    INSERT INTO applications (${COLUMNS.join(', ')})
    VALUES (${COLUMNS.map((c) => `@${c}`).join(', ')})
  `);

  const insertMany = db.transaction((records) => {
    for (const record of records) {
      insert.run(record);
    }
  });

  insertMany(DEMO_RECORDS);
  db.close();

  console.log(`Seeded ${DEMO_RECORDS.length} demo records.`);
  process.exit(0);
} catch (error) {
  console.error(error);
  process.exit(1);
}
