// Side-effect-free demo seed data for the SQLite `applications` table.
//
// Records are in SQLite storage shape: snake_case columns, JSON-stringified
// arrays for `skills` / `preferred_skills` / `timeline`, `fav: 0|1`, `archived: 0|1`.
// The CLI seed script (`server/db-seed.js`) re-imports this constant and
// inserts the rows verbatim. Feature 020's portfolio demo seed
// (`src/data/demoSeed.js`) and parity test
// (`tests/data/demoStore.test.js`) also import this constant — keep this
// file free of any `./db.js` / `better-sqlite3` / `process.exit`
// side effects so the import is safe in both browser-bundle and test
// contexts.
//
// Parity rule: when this array changes, update the demo fixture in
// `src/data/demoSeed.js` in the same PR. The demoStore parity test will
// fail if the two surfaces drift.

const SOURCE_ANCHOR_ISO = '2026-04-26';
const DAY_MS = 86_400_000;

function parseISODate(isoString) {
  const [year, month, day] = isoString.split('-').map(Number);
  return new Date(year, month - 1, day);
}

function toISODate(date = new Date()) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function shiftISODate(isoString) {
  if (!isoString) {
    return isoString;
  }

  const offsetMs = parseISODate(toISODate(new Date())).getTime() - parseISODate(SOURCE_ANCHOR_ISO).getTime();
  return toISODate(new Date(parseISODate(isoString).getTime() + offsetMs));
}

function timeline(entries) {
  return JSON.stringify(entries.map((entry) => ({
    ...entry,
    date: shiftISODate(entry.date),
  })));
}

function shiftRecordDates(record) {
  const shifted = { ...record };

  for (const field of ['application_date', 'last_status_update', 'created_at', 'updated_at']) {
    if (shifted[field]) {
      shifted[field] = shiftISODate(shifted[field]);
    }
  }

  return shifted;
}

const DEMO_TIMELINES = [
  timeline([
    { id: 1, date: '2026-04-10', status: 'applied', text: 'Submitted application through LinkedIn.' },
    { id: 2, date: '2026-04-18', status: 'applied', text: 'Jane confirmed the profile is moving to hiring review.' },
  ]),
  timeline([
    { id: 1, date: '2026-03-28', status: 'applied', text: 'Applied after Indeed recruiter outreach.' },
    { id: 2, date: '2026-04-04', status: 'phone_screen', text: 'Recruiter screen covered backend scope and on-site expectations.' },
    { id: 3, date: '2026-04-18', status: 'interview', text: 'Panel interview scheduled for next week.' },
    { id: 4, date: '2026-04-18', status: 'interview', text: 'Panel completed; send a concise thank-you note.' },
  ]),
  timeline([
    { id: 1, date: '2026-03-15', status: 'applied', text: 'Referral submitted by Maria.' },
    { id: 2, date: '2026-03-22', status: 'phone_screen', text: 'Recruiter screen went well; startup pace confirmed.' },
    { id: 3, date: '2026-04-02', status: 'interview', text: 'Technical interview focused on product launch tradeoffs.' },
    { id: 4, date: '2026-04-22', status: 'offer', text: 'Verbal offer received with five-day decision window.' },
    { id: 5, date: '2026-04-22', status: 'accepted', text: 'Acceptance call tentatively booked after compensation review.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-14', status: 'applied', text: 'Applied through company website.' },
    { id: 2, date: '2026-04-18', status: 'phone_screen', text: 'HR call complete; waiting for technical screen invite.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-05', status: 'applied', text: 'Applied for ML role via LinkedIn.' },
    { id: 2, date: '2026-04-12', status: 'phone_screen', text: 'Priya described recommendation-engine roadmap.' },
    { id: 3, date: '2026-04-19', status: 'assessment', text: 'Take-home assessment assigned; due 2026-04-30.' },
  ]),
  timeline([]),
  timeline([
    { id: 1, date: '2026-03-10', status: 'applied', text: 'Applied as a platform backup option.' },
    { id: 2, date: '2026-03-17', status: 'phone_screen', text: 'Recruiter asked about Java depth.' },
    { id: 3, date: '2026-04-01', status: 'rejected', text: 'Rejected; role required more Java experience.' },
  ]),
  timeline([
    { id: 1, date: '2026-03-05', status: 'applied', text: 'Submitted through the company careers site.' },
    { id: 2, date: '2026-03-12', status: 'phone_screen', text: 'Alex confirmed fintech reliability scope.' },
    { id: 3, date: '2026-03-22', status: 'interview', text: 'Onsite interview completed.' },
    { id: 4, date: '2026-03-29', status: 'interview', text: 'Followed up after one week with no response.' },
    { id: 5, date: '2026-04-05', status: 'ghosted', text: 'Marked ghosted after second follow-up and no response.' },
  ]),
  timeline([
    { id: 1, date: '2026-03-20', status: 'applied', text: 'Referral submitted for React role.' },
    { id: 2, date: '2026-04-23', status: 'withdrawn', text: 'Withdrew after Gamma Digital offer became stronger.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-08', status: 'applied', text: 'Exploratory management application submitted.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-02', status: 'applied', text: 'Submitted SRE application.' },
    { id: 2, date: '2026-04-09', status: 'phone_screen', text: 'Recruiter outreach from Dana; incident-response fit discussed.' },
    { id: 3, date: '2026-04-21', status: 'interview', text: 'Onsite scheduled for reliability and system design.' },
    { id: 4, date: '2026-04-29', status: 'interview', text: 'Future onsite reminder: review incident postmortems.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-16', status: 'applied', text: 'Applied via AngelList.' },
    { id: 2, date: '2026-04-24', status: 'phone_screen', text: 'Recruiter screen done; Swift depth is the stretch area.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-09', status: 'applied', text: 'Applied for data engineering role.' },
    { id: 2, date: '2026-04-16', status: 'phone_screen', text: 'Omar explained SQL and Python assessment format.' },
    { id: 3, date: '2026-04-22', status: 'assessment', text: 'Technical assessment opened; three-hour window.' },
    { id: 4, date: '2026-04-28', status: 'assessment', text: 'Follow-up reminder: submit take-home before deadline.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-25', status: 'wishlisted', text: 'Wishlisted dream staff role for later review.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-10', status: 'applied', text: 'Applied as a backup enterprise Java option.' },
  ]),
  timeline([
    { id: 1, date: '2026-03-18', status: 'applied', text: 'Applied despite embedded experience gap.' },
    { id: 2, date: '2026-04-03', status: 'rejected', text: 'Rejected; C/C++ embedded depth was below requirement.' },
  ]),
  timeline([
    { id: 1, date: '2026-03-25', status: 'applied', text: 'Referral application submitted.' },
    { id: 2, date: '2026-04-10', status: 'withdrawn', text: 'Withdrew after salary and on-site details landed.' },
  ]),
  timeline([
    { id: 1, date: '2026-03-12', status: 'applied', text: 'Applied for cloud architecture track.' },
    { id: 2, date: '2026-03-21', status: 'phone_screen', text: 'Rachel reviewed AWS migration background.' },
    { id: 3, date: '2026-04-04', status: 'interview', text: 'Architecture interview covered network segmentation.' },
    { id: 4, date: '2026-04-20', status: 'offer', text: 'Offer received; useful for negotiation.' },
  ]),
  timeline([
    { id: 1, date: '2026-03-22', status: 'applied', text: 'Applied through security careers page.' },
    { id: 2, date: '2026-03-30', status: 'interview', text: 'Technical screen completed.' },
    { id: 3, date: '2026-04-06', status: 'interview', text: 'Followed up once after no response.' },
    { id: 4, date: '2026-04-10', status: 'ghosted', text: 'Marked ghosted after silence from Victor.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-18', status: 'applied', text: 'Applied through AngelList.' },
    { id: 2, date: '2026-04-24', status: 'phone_screen', text: 'Nadia recruiter screen covered Series B pace.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-01', status: 'applied', text: 'Applied for client-facing solutions role.' },
    { id: 2, date: '2026-04-11', status: 'phone_screen', text: 'Recruiter outreach clarified travel expectations.' },
    { id: 3, date: '2026-04-19', status: 'interview', text: 'Technical discovery interview scheduled.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-21', status: 'applied', text: 'Applied to broaden the network engineering pipeline.' },
  ]),
  timeline([
    { id: 1, date: '2026-04-26', status: 'wishlisted', text: 'Wishlisted recently posted frontend architecture role.' },
  ]),
];

const BASE_DEMO_RECORDS = [
  {
    company_name: 'Acme Corp',
    job_title: 'Frontend Engineer',
    status: 'applied',
    compat: 85,
    fav: 1,
    salary: 120000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/acme-fe',
    recruiter: 'Jane Smith',
    notes: 'Strong culture fit. Hybrid role, 2 days in office.',
    responsibilities: 'Shape a shared React design system for a corporate hiring platform, pairing Storybook governance with pragmatic accessibility reviews.',
    skills: JSON.stringify(['React', 'TypeScript', 'CSS', 'Vite']),
    application_date: '2026-04-10',
    last_status_update: '2026-04-18',
    created_at: '2026-04-10',
    updated_at: '2026-04-18',
    archived: 0,
    location: 'Makati',
    shift: 'Day',
    work_setup: 'Hybrid',
    compat_notes: 'Strong React match; culture fit confirmed.',
    general_notes: null,
    preferred_skills: JSON.stringify(['Storybook', 'Accessibility']),
  },
  {
    company_name: 'Beta Systems',
    job_title: 'Backend Engineer',
    status: 'interview',
    compat: 72,
    fav: 0,
    salary: 130000,
    source_platform: 'Indeed',
    job_posting_url: 'https://jobs.example.com/beta-backend',
    recruiter: 'Tom Lee',
    notes: 'Second round scheduled for next week. Panel format.',
    responsibilities: 'Steward order-management APIs for a regional logistics group, using PostgreSQL migration playbooks and calm on-call runbooks.',
    skills: JSON.stringify(['Node.js', 'PostgreSQL', 'Docker', 'AWS']),
    application_date: '2026-03-28',
    last_status_update: '2026-04-18',
    created_at: '2026-03-28',
    updated_at: '2026-04-18',
    archived: 0,
    location: 'BGC',
    shift: 'Day',
    work_setup: 'On-site',
    compat_notes: null,
    general_notes: 'Second round prep needed.',
    preferred_skills: null,
  },
  {
    company_name: 'Gamma Digital',
    job_title: 'Full Stack Developer',
    status: 'offer',
    compat: 91,
    fav: 1,
    salary: 145000,
    source_platform: 'Referral',
    job_posting_url: null,
    recruiter: 'Maria Chen',
    notes: 'Verbal offer received. Five-day response window in progress.',
    responsibilities: 'Guide two startup product pods from discovery to launch, splitting time between React workflows, Node services, and release decisions.',
    skills: JSON.stringify(['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Redis']),
    application_date: '2026-03-15',
    last_status_update: '2026-04-22',
    created_at: '2026-03-15',
    updated_at: '2026-04-22',
    archived: 0,
    location: null,
    shift: 'Flexible',
    work_setup: 'Remote',
    compat_notes: 'Best overall fit of current round.',
    general_notes: null,
    preferred_skills: JSON.stringify(['GraphQL', 'Redis']),
  },
  {
    company_name: 'Delta Cloud',
    job_title: 'DevOps Engineer',
    status: 'phone_screen',
    compat: 60,
    fav: 0,
    salary: 110000,
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/delta-devops',
    recruiter: null,
    notes: 'Initial call with HR went well. Waiting for technical screen invite.',
    responsibilities: 'Harden deployment paths for a cloud infrastructure team, tuning Terraform modules, GKE clusters, and incident drills.',
    skills: JSON.stringify(['Kubernetes', 'Terraform', 'GCP', 'Python']),
    application_date: '2026-04-14',
    last_status_update: '2026-04-18',
    created_at: '2026-04-14',
    updated_at: '2026-04-18',
    archived: 0,
    location: null,
    shift: 'Mid',
    work_setup: 'Hybrid',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Epsilon AI',
    job_title: 'ML Engineer',
    status: 'assessment',
    compat: 78,
    fav: 0,
    salary: 150000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/epsilon-ml',
    recruiter: 'Priya Nair',
    notes: 'Take-home project due 2026-04-30. Build a small recommendation engine.',
    responsibilities: 'Operationalize recommendation models for a consumer AI group, moving PyTorch experiments into MLflow-tracked production jobs.',
    skills: JSON.stringify(['Python', 'PyTorch', 'SQL', 'MLflow']),
    application_date: '2026-04-05',
    last_status_update: '2026-04-19',
    created_at: '2026-04-05',
    updated_at: '2026-04-19',
    archived: 0,
    location: 'Ortigas',
    shift: 'Day',
    work_setup: 'Remote',
    compat_notes: 'Good ML stack overlap.',
    general_notes: 'Take-home due soon.',
    preferred_skills: JSON.stringify(['TensorFlow', 'Kubeflow']),
  },
  {
    company_name: 'Zeta Health',
    job_title: 'Software Engineer',
    status: 'wishlisted',
    compat: 55,
    fav: 0,
    salary: null,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/zeta-swe',
    recruiter: null,
    notes: 'Interesting mission. Not ready to apply — revisit after current round.',
    responsibilities: 'Map patient-facing workflow risks before applying, comparing Django service boundaries with the health-tech team mission.',
    skills: JSON.stringify(['Python', 'Django', 'React']),
    application_date: null,
    last_status_update: '2026-04-23',
    created_at: '2026-04-23',
    updated_at: '2026-04-23',
    archived: 0,
    location: null,
    shift: null,
    work_setup: null,
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Eta Retail',
    job_title: 'Platform Engineer',
    status: 'rejected',
    compat: 40,
    fav: 0,
    salary: 115000,
    source_platform: 'Indeed',
    job_posting_url: null,
    recruiter: 'Chris Park',
    notes: 'Generic rejection email. Role required more Java experience.',
    responsibilities: 'Modernize developer tooling for a retail engineering department, replacing manual Java release steps with Kafka-aware platform services.',
    skills: JSON.stringify(['Java', 'Spring Boot', 'Kafka']),
    application_date: '2026-03-10',
    last_status_update: '2026-04-01',
    created_at: '2026-03-10',
    updated_at: '2026-04-01',
    archived: 0,
    location: 'Manila',
    shift: 'Night',
    work_setup: 'On-site',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Theta Finance',
    job_title: 'Senior Engineer',
    status: 'ghosted',
    compat: 65,
    fav: 0,
    salary: 140000,
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/theta-sre',
    recruiter: 'Alex Wong',
    notes: 'No response after onsite interview on 2026-03-22. Followed up twice.',
    responsibilities: 'Drive reliability reviews across fintech payment services, mentoring senior peers on Go tracing, SLO budgets, and database failover.',
    skills: JSON.stringify(['Go', 'Kubernetes', 'Prometheus', 'PostgreSQL']),
    application_date: '2026-03-05',
    last_status_update: '2026-03-22',
    created_at: '2026-03-05',
    updated_at: '2026-04-05',
    archived: 0,
    location: null,
    shift: null,
    work_setup: 'Remote',
    compat_notes: null,
    general_notes: 'Followed up twice; no response.',
    preferred_skills: null,
  },
  {
    company_name: 'Iota Media',
    job_title: 'React Developer',
    status: 'withdrawn',
    compat: 50,
    fav: 0,
    salary: 105000,
    source_platform: 'Referral',
    job_posting_url: null,
    recruiter: 'Sam Rivera',
    notes: 'Withdrew after receiving the Gamma Digital offer.',
    responsibilities: 'Craft high-traffic streaming interfaces for a media subscription product, balancing GraphQL data needs with Next.js performance budgets.',
    skills: JSON.stringify(['React', 'GraphQL', 'Next.js']),
    application_date: '2026-03-20',
    last_status_update: '2026-04-23',
    created_at: '2026-03-20',
    updated_at: '2026-04-23',
    archived: 0,
    location: null,
    shift: 'Night',
    work_setup: 'Remote',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Kappa Labs',
    job_title: 'Engineering Manager',
    status: 'applied',
    compat: 68,
    fav: 0,
    salary: 160000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/kappa-em',
    recruiter: null,
    notes: 'Exploratory — not actively pursuing management yet.',
    responsibilities: 'Coach a six-person data platform team through roadmap planning, hiring calibration, and Python service ownership.',
    skills: JSON.stringify(['Team leadership', 'Node.js', 'Python']),
    application_date: '2026-04-08',
    last_status_update: '2026-04-08',
    created_at: '2026-04-08',
    updated_at: '2026-04-08',
    archived: 1,
    location: null,
    shift: null,
    work_setup: 'Hybrid',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Lambda Ops',
    job_title: 'Site Reliability Engineer',
    status: 'interview',
    compat: 70,
    fav: 0,
    salary: 135000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/lambda-sre',
    recruiter: 'Dana Hill',
    notes: 'Onsite scheduled for 2026-04-29. Will cover incident response and system design.',
    responsibilities: 'Set reliability targets for core operations services, turning PagerDuty trends and Grafana dashboards into post-incident improvements.',
    skills: JSON.stringify(['Go', 'Prometheus', 'Grafana', 'Kubernetes', 'PagerDuty']),
    application_date: '2026-04-02',
    last_status_update: '2026-04-21',
    created_at: '2026-04-02',
    updated_at: '2026-04-21',
    archived: 0,
    location: null,
    shift: 'Day',
    work_setup: 'Remote',
    compat_notes: 'Strong reliability background.',
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Mu Technologies',
    job_title: 'iOS Developer',
    status: 'phone_screen',
    compat: 58,
    fav: 0,
    salary: 115000,
    source_platform: 'AngelList',
    job_posting_url: 'https://jobs.example.com/mu-ios',
    recruiter: 'Lena Park',
    notes: 'Recruiter screen done. Stretch role — Swift experience is limited.',
    responsibilities: 'Deliver SwiftUI features for a mobile startup, negotiating API contracts with backend engineers before each App Store release.',
    skills: JSON.stringify(['Swift', 'SwiftUI', 'Xcode', 'REST APIs']),
    application_date: '2026-04-16',
    last_status_update: '2026-04-24',
    created_at: '2026-04-16',
    updated_at: '2026-04-24',
    archived: 0,
    location: null,
    shift: 'Mid',
    work_setup: 'On-site',
    compat_notes: null,
    general_notes: 'Stretch role.',
    preferred_skills: null,
  },
  {
    company_name: 'Nu Analytics',
    job_title: 'Data Engineer',
    status: 'assessment',
    compat: 82,
    fav: 0,
    salary: 125000,
    source_platform: 'Indeed',
    job_posting_url: 'https://jobs.example.com/nu-de',
    recruiter: 'Omar Hassan',
    notes: 'SQL + Python take-home. 3-hour window, due 2026-04-28.',
    responsibilities: 'Design analytics pipelines for a data consultancy, orchestrating Airflow, dbt, and BigQuery models for finance and growth teams.',
    skills: JSON.stringify(['Python', 'dbt', 'Airflow', 'BigQuery', 'SQL']),
    application_date: '2026-04-09',
    last_status_update: '2026-04-22',
    created_at: '2026-04-09',
    updated_at: '2026-04-22',
    archived: 0,
    location: 'BGC',
    shift: 'Day',
    work_setup: 'Hybrid',
    compat_notes: 'Solid data engineering match.',
    general_notes: null,
    preferred_skills: JSON.stringify(['Spark', 'Looker']),
  },
  {
    company_name: 'Xi Studio',
    job_title: 'Staff Engineer',
    status: 'wishlisted',
    compat: 83,
    fav: 1,
    salary: 170000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/xi-staff',
    recruiter: null,
    notes: 'Dream role — wait until current round settles before applying.',
    responsibilities: 'Evaluate staff-level architecture work for a distributed systems studio, with emphasis on TypeScript boundaries and Go services.',
    skills: JSON.stringify(['System design', 'TypeScript', 'Go', 'Distributed systems']),
    application_date: null,
    last_status_update: '2026-04-25',
    created_at: '2026-04-25',
    updated_at: '2026-04-25',
    archived: 0,
    location: null,
    shift: null,
    work_setup: 'Remote',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Omicron Bank',
    job_title: 'Java Developer',
    status: 'applied',
    compat: 48,
    fav: 0,
    salary: 118000,
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/omicron-java',
    recruiter: null,
    notes: 'Applied as a backup option. Heavy enterprise Java stack.',
    responsibilities: 'Refactor compliance-heavy banking services in Spring Boot, keeping Oracle-backed payment flows auditable and predictable.',
    skills: JSON.stringify(['Java', 'Spring Boot', 'Oracle DB', 'Maven']),
    application_date: '2026-04-17',
    last_status_update: '2026-04-10',
    created_at: '2026-04-17',
    updated_at: '2026-04-10',
    archived: 0,
    location: 'Makati',
    shift: 'Day',
    work_setup: 'On-site',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Pi Robotics',
    job_title: 'Embedded Software Engineer',
    status: 'rejected',
    compat: 35,
    fav: 0,
    salary: 110000,
    source_platform: 'Indeed',
    job_posting_url: null,
    recruiter: 'Ingrid Sato',
    notes: 'Required 3+ years of C/C++ embedded experience. Not a match.',
    responsibilities: 'Implement embedded control loops for robotics hardware, validating RTOS timing assumptions on ARM prototypes.',
    skills: JSON.stringify(['C', 'C++', 'RTOS', 'ARM']),
    application_date: '2026-03-18',
    last_status_update: '2026-04-03',
    created_at: '2026-03-18',
    updated_at: '2026-04-03',
    archived: 0,
    location: null,
    shift: null,
    work_setup: 'Field',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Rho Games',
    job_title: 'Game Developer',
    status: 'withdrawn',
    compat: 44,
    fav: 0,
    salary: 95000,
    source_platform: 'Referral',
    job_posting_url: null,
    recruiter: 'Jake Moon',
    notes: 'Withdrew — salary range too low and fully on-site.',
    responsibilities: 'Prototype Unity gameplay loops for a mobile game studio, coordinating C# systems work with design telemetry.',
    skills: JSON.stringify(['C#', 'Unity', 'Git', 'Agile']),
    application_date: '2026-03-25',
    last_status_update: '2026-04-10',
    created_at: '2026-03-25',
    updated_at: '2026-04-10',
    archived: 0,
    location: null,
    shift: null,
    work_setup: 'On-site',
    compat_notes: null,
    general_notes: 'Salary too low; fully on-site.',
    preferred_skills: null,
  },
  {
    company_name: 'Sigma Cloud',
    job_title: 'Cloud Architect',
    status: 'offer',
    compat: 88,
    fav: 1,
    salary: 165000,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/sigma-arch',
    recruiter: 'Rachel Kim',
    notes: 'Competing offer — using to negotiate with Gamma Digital.',
    responsibilities: 'Architect a multi-region AWS migration for enterprise workloads, using CDK patterns and network segmentation reviews.',
    skills: JSON.stringify(['AWS', 'Terraform', 'Python', 'CDK', 'Networking']),
    application_date: '2026-03-12',
    last_status_update: '2026-04-20',
    created_at: '2026-03-12',
    updated_at: '2026-04-20',
    archived: 0,
    location: null,
    shift: 'Flexible',
    work_setup: 'Remote',
    compat_notes: 'Strong cloud match.',
    general_notes: 'Competing offer; using for negotiation.',
    preferred_skills: JSON.stringify(['CDK', 'CloudFormation']),
  },
  {
    company_name: 'Tau Security',
    job_title: 'Security Engineer',
    status: 'ghosted',
    compat: 74,
    fav: 0,
    salary: 140000,
    source_platform: 'Company website',
    job_posting_url: 'https://jobs.example.com/tau-sec',
    recruiter: 'Victor Olsen',
    notes: 'Completed technical screen on 2026-03-30. No word since.',
    responsibilities: 'Lead security reviews for SaaS delivery teams, combining OWASP threat models, Burp Suite findings, and AWS control checks.',
    skills: JSON.stringify(['Python', 'Burp Suite', 'OWASP', 'AWS Security']),
    application_date: '2026-03-22',
    last_status_update: '2026-03-30',
    created_at: '2026-03-22',
    updated_at: '2026-04-10',
    archived: 0,
    location: null,
    shift: 'Mid',
    work_setup: 'Remote',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Upsilon Dev',
    job_title: 'Software Engineer II',
    status: 'phone_screen',
    compat: 76,
    fav: 0,
    salary: 125000,
    source_platform: 'AngelList',
    job_posting_url: 'https://jobs.example.com/upsilon-swe2',
    recruiter: 'Nadia Flores',
    notes: 'Fast-growing Series B. Engineering team of 15.',
    responsibilities: 'Build first-version collaboration features for a Series B startup, moving quickly across React, Node.js, and PostgreSQL.',
    skills: JSON.stringify(['TypeScript', 'React', 'Node.js', 'PostgreSQL']),
    application_date: '2026-04-18',
    last_status_update: '2026-04-24',
    created_at: '2026-04-18',
    updated_at: '2026-04-24',
    archived: 0,
    location: null,
    shift: 'Day',
    work_setup: 'Remote',
    compat_notes: null,
    general_notes: 'Fast-growing Series B.',
    preferred_skills: null,
  },
  {
    company_name: 'Phi Systems',
    job_title: 'Solutions Architect',
    status: 'interview',
    compat: 66,
    fav: 0,
    salary: 155000,
    source_platform: 'LinkedIn',
    job_posting_url: null,
    recruiter: 'Marcus Bell',
    notes: 'Client-facing role — heavier travel than expected. Worth exploring.',
    responsibilities: 'Translate enterprise integration needs into Salesforce and AWS solution diagrams during client-facing technical discovery.',
    skills: JSON.stringify(['AWS', 'Salesforce', 'REST APIs', 'Solution design']),
    application_date: '2026-04-01',
    last_status_update: '2026-04-19',
    created_at: '2026-04-01',
    updated_at: '2026-04-19',
    archived: 0,
    location: 'Makati',
    shift: 'Flexible',
    work_setup: 'Hybrid',
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Chi Networks',
    job_title: 'Senior Network Engineer',
    status: 'applied',
    compat: 42,
    fav: 0,
    salary: 120000,
    source_platform: 'Indeed',
    job_posting_url: 'https://jobs.example.com/chi-net',
    recruiter: null,
    notes: 'Long shot — applied to broaden the pipeline.',
    responsibilities: 'Plan resilient enterprise network upgrades, documenting BGP routing choices and security handoffs for operations teams.',
    skills: JSON.stringify(['Cisco', 'BGP', 'OSPF', 'Network security']),
    application_date: '2026-04-21',
    last_status_update: '2026-04-21',
    created_at: '2026-04-21',
    updated_at: '2026-04-21',
    archived: 0,
    location: null,
    shift: null,
    work_setup: null,
    compat_notes: null,
    general_notes: null,
    preferred_skills: null,
  },
  {
    company_name: 'Psi Corp',
    job_title: 'Frontend Architect',
    status: 'wishlisted',
    compat: 79,
    fav: 0,
    salary: null,
    source_platform: 'LinkedIn',
    job_posting_url: 'https://jobs.example.com/psi-fe-arch',
    recruiter: null,
    notes: 'Posted recently. Revisit after the current interview round wraps.',
    responsibilities: 'Research frontend architecture requirements before applying, focusing on micro-frontend governance and TypeScript migration scope.',
    skills: JSON.stringify(['React', 'Micro-frontends', 'Design systems', 'TypeScript']),
    application_date: null,
    last_status_update: '2026-04-26',
    created_at: '2026-04-26',
    updated_at: '2026-04-26',
    archived: 0,
    location: null,
    shift: 'Night',
    work_setup: 'Remote',
    compat_notes: 'Interesting frontend architecture scope.',
    general_notes: null,
    preferred_skills: JSON.stringify(['Webpack', 'Module federation']),
  },
];

export const DEMO_RECORDS = BASE_DEMO_RECORDS.map((record, index) => ({
  ...shiftRecordDates(record),
  timeline: DEMO_TIMELINES[index],
}));
